spring.application.name=sensitive-words-service
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=sanitization_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sanitization_app
spring.datasource.password=strongPassword123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=sanitization

# Internal Authentication
internal.auth.admin.username=admin
internal.auth.admin.password=Admin123

internal.auth.user.username=user
internal.auth.user.password=User123